# Generated by Django 6.1.1 on 2026-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='routing_fue_state_a0c837_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='routing_fue_latitud_6dc999_idx',
        ),
        migrations.AddConstraint(
            model_name='fuelstation',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='fuel_station_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelstation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), name='fuel_station_coordinates_valid'),
        ),
    ]
